export const INCREMENT_COUNTER = 'INCREMENT_COUNTER';
export const DECREMENT_COUNTER = 'DECREMENT_COUNTER';

export const CLEAR_COUNTER_PENDING = 'CLEAR_COUNTER_PENDING';
export const CLEAR_COUNTER_SUCCESS = 'CLEAR_COUNTER_SUCCESS';
export const CLEAR_COUNTER_FAILURE = 'CLEAR_COUNTER_FAILURE';
